nsf:
  config:
    enable: true
    server: {replace with your nsf-config-server url}
      namespaces:
        - name: application
          Private: true
  type: http
  version: '2.0'
  nsfServer: 'http://nsf-server-cust56.netease.com'
  application:
    name: product-service
    version: 0.0.1
    projectCode: gldq-default
    envCode: prod
    zone: default
    group: default
    tags: []
  authority:
    accessKey: 7c6897fc06a84247a195df86dd9eb0d7
    secretKey: cf6f0c19672c4f75b99f73b0e238604d
  manager:
    patterns: []
